import Head from "next/head";
import estilos from "@/styles/Home.module.css";
import Image from "next/image";
import Link from "next/link";

import Rodape from "@/componentes/Rodape";
import SecaoCapa from "@/componentes/SecaoCapa";
import SecaoContato from "@/componentes/SecaoContatos";
import SecaoProdutos from "@/componentes/SecaoProdutos";
import SecaoSobre from "@/componentes/SecaoSobre";
import Topo from "@/componentes/Topo";

export default function Home() {
  return (
    <>
      <Head>
        <title>Óticas vida - Loja de óculos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topo/>
      <SecaoCapa/>
      <SecaoProdutos/>
      <SecaoSobre/>
      <SecaoContato/>
      <Rodape/>
    </>
  );
}
